### ISSUE TITLE
Ajouter les endpoints de l'api dans un fichier markdown sur le repo

### ISSUE THREAD

**Issue by GODOmegaPi** [Note-thing/backend#24]
Il serait utile d'avoir un fichier d'écrivant les endpoints de notre api avec leur paramètre et le format des réponses

**Comment by EricB2A** [comment]
Bonjour Guillaume, 

C'est en effet intéressant de mettre en place une documentation technique. Cependant, cette étape viendrait plus tard étant donné que la spec risque de changer en l’intégrant avec l’application frontend.

**Comment by noahfusi** [comment]
Fait dans le wiki
