### ISSUE TITLE
Rajouter la variabe d'environnement JWT_SECRET dans le CI

### ISSUE THREAD

**Issue by GODOmegaPi** [Note-thing/backend#25]

**Comment by EricB2A** [comment]
Bonjour Guillaume, 

Serait-il possible d'être plus précis sur la nature du problème ?

**Comment by GODOmegaPi** [comment]
Je me suis rendus compte que le problème que j'avais identifié n'étais pas provoquer par le code mais par l’oubli de la clef secret pour le JWT ce qui provoque des erreurs quand le CD lance les tests d'intégration. Le problème doit quand même être résolu en ajoutant une variable dans Github secrets et de la référencer dans le CD.

**Comment by EricB2A** [comment]
D'accord, donc si je comprend bien ton issue, il manque juste le variable d'environnement `JWT_SECRET` à la CI.
Je regarde ça mais c'est pas le plus urgent à mon sens.

**Comment by EricB2A** [comment]
Ok ok, bon visiblement on parvient à lancer des tests avec un secret JWT. Je ferme donc l'issue.
N'hésite pas à réouvrir et à me ping si tu vois un problème dans la CI.
