### ISSUE TITLE
Ajouter le support de Cross Origin requests pour l'accès par le frontend

### ISSUE THREAD

**Issue by GODOmegaPi** [Note-thing/backend#29]
- [ ] CORS installé
- [ ] CORS configurer pour GET, POST, PUT, DELETE

Les fetch du frontend ne vont pas fonctionner temps que le CORS n'est pas configurer. Une solution simple et efficace est d'installer [rack-cors gem](https://github.com/cyu/rack-cors) et de le configurer pour permettre le Cross-Origin.

**Comment by EricB2A** [comment]
Yo, 

Les requêtes CORS ne vont poser problème que sur un environnement de développement (une fois déployé, les requêtes passent par le reverse proxy -> même domaine... à vérifier bien sûr).
Du coup, si ça concerne ton environnement de développement je te laisse mettre en place la gem en local ;) 
Tu peux demander à @Double-i comment faire, il a eu le même problème il y a quelques semaines !
