### ISSUE TITLE
Tests 

### ISSUE THREAD

**Issue by EricB2A** [Note-thing/backend#56]
Voici les endpoints qui doivent être testés :

- [x]  GET, POST, GET (avec `id`), PATCH, PUT, DELETE `/api/v1/tags`
- [x] GET, POST, PUT, DELETE, GET(avec `id`) `/api/v1/notes`
- [x] POST, PATCH, PUT, DELETE, GET `/api/v1/folders`
- [x] GET `/api/v1/structure`
- [x] GET `/api/v1/notes/:id/shared_notes`
- [x] CRUD `/api/v1/notes`
- [x] POST `/api/v1/shared_notes/:uuid/cop`
- [x] POST, GET, DELETE `/api/v1/shared_notes`
- [x] POST `/api/v1/signin`
- [x] POST `/api/v1/signup`
- [x] POST `/api/v1/password/forgot`
- [x] POST `/api/v1/password/reset`

Les tests seront réalisés à la fin de l'itération, afin que nous soyons sûrs que la spec ne change plus.

**Comment by EricB2A** [comment]
J'en profite pour mentionner que certains tests ne semblent pas fonctionner. 
Il faudrait regarder ça.

**Comment by noahfusi** [comment]
Les tests concernant :
/api/v1/signup
/api/v1/password/forgot
/api/v1/password/reset
Ne sont pas réalisables dû à l'utilisation de la validation par email

**Comment by noahfusi** [comment]
Tous les endpoints ont été testés
